name: Node.js CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del c贸digo
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependencias
        run: npm install

      - name: Dar permisos y ejecutar pruebas
        run: |
          chmod +x ./node_modules/.bin/jest
          npx jest --runInBand

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: success()

    steps:
      - name: Checkout del c贸digo
        uses: actions/checkout@v3

      - name: Simular despliegue local
        run: |
          echo "Iniciando despliegue simulado..."
          echo "Compilando aplicaci贸n..."
          echo "Copiando archivos al entorno local (simulaci贸n)..."
          echo "Reiniciando servidor simulado..."
          echo "Despliegue completado correctamente."
